### ISSUE TITLE
"Something went wrong while processing your request!" error upon fresh installation

### ISSUE THREAD

**Issue by connecteev** [the94air/laravel-ajax-crud#3]
After a fresh installation, running ```php artisan serve``` and going to http://127.0.0.1:8000:

I see this error message:
Screenshot: https://1ce.org/1#ByzyuuofB

Message on the front-end:
```
Something went wrong while processing your request!
```

Error message in console
```
OPTIONS https://127.0.0.1:8000/items net::ERR_CONNECTION_CLOSED
```

FYI This same error is seen even if I try to create an item and hit submit...looks like everything is broken, or there is some install step missing that I'm unaware of.

Btw I see this in the terminal window (I'm running on http, not https - not sure if this is the problem but if so, the code *should* work on both)
```
[Sun Jul 28 12:30:14 2019] 127.0.0.1:54685 Invalid request (Unsupported SSL request)
[Sun Jul 28 12:30:14 2019] 127.0.0.1:54686 Invalid request (Unsupported SSL request)
[Sun Jul 28 12:30:15 2019] 127.0.0.1:54693 [200]: /favicon.ico
[Sun Jul 28 12:32:32 2019] 127.0.0.1:55346 [200]: /favicon.ico
[Sun Jul 28 12:32:36 2019] 127.0.0.1:55363 [200]: /favicon.ico
[Sun Jul 28 12:32:36 2019] 127.0.0.1:55368 Invalid request (Unsupported SSL request)
[Sun Jul 28 12:32:36 2019] 127.0.0.1:55369 Invalid request (Unsupported SSL request)
```

**Comment by the94air** [comment]
Hello, I think there are an https redirect middleware. Try to disable it in kernal.php.

**Comment by connecteev** [comment]
@the94air I dont see any redirects in the kernel.php file: https://github.com/the94air/laravel-ajax-crud/blob/master/app/Http/Kernel.php

**Comment by the94air** [comment]
Sorry for the late reply. It looks like I'm forcing HTTPS on the `AppServiceProvider.php`
https://github.com/the94air/laravel-ajax-crud/blob/5777c5fbc376579afd6774347259c952cbbb1563/app/Providers/AppServiceProvider.php#L20-L28

**Comment by the94air** [comment]
I think this fixes you issue.
